[webserver]
bind_addr = ":8080"
logger_level = "debug"
[store]
database_uri = "host=DB_HOST port=DB_PORT user=DB_USER password=DB_PASSWORD name=DB_NAME sslmode=disable"
DB_USER=aleksandr
DB_PASSWORD=pwd1234
DB_NAME=hw15_go_sql
DB_HOST=localhost
DB_PORT=5432